### ISSUE TITLE
Anamorphosis_Cylindrical_Polar crashes with 64-bit ImageJ 1.50i on Windows 10 

### ISSUE THREAD

**Issue by emerzn** [phillipkent/AnamorphMeIJ#1]
When trying to use this plugin with the most recent ImageJ on the attached image, I get the following error:

> ImageJ 1.50i; Java 1.8.0_77 [64-bit]; Windows 10 10.0; 26MB of 6100MB (<1%)
> 
> java.lang.NullPointerException
>   at Anamorphosis_Cylindrical_Polar.run(Anamorphosis_Cylindrical_Polar.java:101)
>   at ij.IJ.runUserPlugIn(IJ.java:216)
>   at ij.IJ.runUserPlugIn(IJ.java:229)
>   at ij.IJ.runPlugIn(IJ.java:180)
>   at ij.Executer.runCommand(Executer.java:137)
>   at ij.Executer.run(Executer.java:66)
>   at java.lang.Thread.run(Unknown Source)

![usa](https://cloud.githubusercontent.com/assets/6620417/18684022/534b08f0-7f38-11e6-90d1-acf3678c4815.jpg)

**Comment by xav-ie** [comment]
Do not waste your time trying to get this to work.. Most of the functions are not even implemented yet and it is ridden with bugs! I instead ran a windows 7 VM with Oracle Box. You can get a free windows vm [here](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/).

I found best results with Oracle VM, the others are trash. It works on all platforms and can be found [here](https://www.virtualbox.org/).

Once you choose "IE8 on Win7" and "Virtual Box" as the format of the download, you'll need to get [Virtual Box Guest Editions](https://oracle-virtualbox.net/faq/15-how-to-use-a-shared-folder-in-virtualbox.html) for file sync between your VM and computer to work (unless you want to use Google Drive).

Finally, you can transfer over the ORIGINAL C++ software executable for Windows found [here](https://www.anamorphosis.com/anamorphme02.zip).

Simply run the executable (at this point you should have Oracle Guest Additions working) and input your images from local machine through a shared folder.

You can put these generated images back on host and use [this software](https://facultyfp.salisbury.edu/despickler/personal/ImagePrinter.html) by Dr. Don Spickler for printing the anamorphized photos. 

Hope this helps.

I am working on making a JavaScript version of this program based on [this paper](https://facultyfp.salisbury.edu/despickler/personal/resources/technologyworkshops/sciencenight2011/sciencenightsu_math.pdf) and will update my answer if I ever get it working!
